### ISSUE TITLE
Tab \t not rendered in static build of pages

### ISSUE THREAD

**Issue by matthew-brett** [ehmatthes/intro_programming#110]
By the way - what a beautiful resource - thank you very much for building it.

I noticed reading `var_string_num.ipynb` that this sentence:

```
The two-character combination "\t" makes a tab appear in a string.
```

renders at http://introtopython.org/var_string_num.html with an empty string instead of `"\t"`.

**Comment by ehmatthes** [comment]
Thanks, I just saw this. I'll be updating the project soon, and I'll take care of this quickly when I do.

**Comment by ehmatthes** [comment]
This appears to be fixed, I think inadvertently by the work to update infrastructure to IPython 3. It might creep back in as I update css files, but I'll keep an eye out for it.
