### ISSUE TITLE
Notebook Critique: Mapping Global Earthquake Activity

### ISSUE THREAD

**Issue by ehmatthes** [ehmatthes/intro_programming#34]
Please share any feedback on this [notebook](http://introtopython.org/visualization_earthquakes.html), particularly any suggestions on how to clarify or improve the installation and setup instructions.

**Comment by HughP** [comment]
This example is awesome. Exactly what I needed. I wish it was part of the documentation or linked from the documentation.

**Comment by ehmatthes** [comment]
Thanks! I'm going to do some significant work on the introtopython project this spring, and your feedback is motivating!

**Comment by HughP** [comment]
One quick question, I copied the Script for the map, and downloaded the data source. I get a fail notice on PIL. Have you tried to build the map with Pillow 2.7.0 yet to see if this is a matplotlib issue with Pillow 2.7.0? I don't think it is your script, but I was just wondering if it is my setup or a combination of new module versions with dependencies on older versions.
My set up is: OSX 10.9.5 Python 2.7.9 Pillow 2.7.0

**Comment by ehmatthes** [comment]
Change the variable map to something like eq_map, to avoid overriding the builtin function map(). See [comment here](https://peak5390.wordpress.com/2012/12/08/matplotlib-basemap-tutorial-plotting-points-on-a-simple-map/#comment-1831).

**Comment by ehmatthes** [comment]
Add instructions for setting up the project on OS X (and Windows), and test project as well.

**Comment by ehmatthes** [comment]
Closing this, because the project has been updated and I'm moving away from issues for specific notebooks that don't have any current open issues.
