### ISSUE TITLE
In-browser Python editor

### ISSUE THREAD

**Issue by bkamapantula** [ehmatthes/intro_programming#89]
@ehmatthes 
I am wondering if you have considered an in-browser editor like Skulpt [1]. This will be useful for students to test code live.

I have attached a screenshot for the same. This is a crude hack. I included example code after generating html.

[1] http://www.skulpt.org/
![intro_programming_skulpt](https://cloud.githubusercontent.com/assets/1143687/2897644/42b3ef92-d586-11e3-8a6d-1277a62c285b.png)

**Comment by ehmatthes** [comment]
This is not a current priority.
